### ISSUE TITLE
Not able to set to USD and showing NULL coin and all zeros

### ISSUE THREAD

**Issue by Marvin-YYC** [hpsaturn/crypto-panel#12]
Thanks for help up and contribute to Crypto News project. Please edit and fill this template.

Thank you for sharing this project

## Description
I used your web installer before for this project a couple years ago, and it worked without a problem.   I just installed it today and I was not able to set the currency to USD and everything else shows NULL or zero.  
It connects to WiFi correctly, and  I was able to set the time zone and sleep time.  The Crypto News is working too.  
Not sure if I have done something wrong or if there is an error with the api??

![signal-2024-11-10-105436](https://github.com/user-attachments/assets/9cd3d7fd-faa3-4ec1-9845-068e97290b22)

## Debug output
If this apply

## Device config
If this apply

**Comment by hpsaturn** [comment]
Thanks Marvin. Only one question, are you entered the coins? at least three, right? maybe can you publish the CLI output please. Today in the night I'm going to review this issue in my panel.. maybe I didn't a test with flash cleared.

**Comment by hpsaturn** [comment]
I notice two things that maybe are bugs with this version:

- You need set the WiFi at the end. (in the old video guide was in the beginning)
- The wipe command is not working well. Maybe do you need wipe to factory defaults with other tool or with esptool or with the webinstaler.

But in the other hand, it is working. I did the next steps:

- I installed the base firmware with the web installer (it still working, I can't believe it)
- added the wifi: scan, setSSID xxx, setPASW xxx, connect
- added 3 coins with curAdd command
- After that, the cpanel fetch the OTA update and it reboots automatically.
- It enter again to the setup with the last button in the right
- I added the temperature of my room for better eInk colors. setTemp 23 (in Celsius)
- added the time zone, for instance for me:  <-05>5
- setSleep to 1h, I mean, 600 seconds (for improve battery consumption)
- and finally setBase usd
- reboot

and it is working. Please check that and please confirm in your case.

**Comment by Marvin-YYC** [comment]
Oh gosh, So sorry.  I just realized my error.  I didn't use google chrome.  .. ..  :(

I just tried it again with google chrome and it is working fine.  

My apologies :(

**Comment by hpsaturn** [comment]
No problem. Checking that, I found some issues. And also in my previous commentary I had a mistake, the setSleep command receive minutes, not seconds. I need notify that in the confirmation of this command. Thanks for report it and for using this firmware.
